[project]
name = "wsl-setup"
requires-python = ">=3.12"

dependencies = []

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
yamllint = "^1.37.0"
ansible = "^13.0.0"
ansible-lint = "^25.2.1"
