---
omz_install_dir: "/home/{{ ansible_user }}/.oh-my-zsh"
omz_theme_dir: "{{ omz_install_dir }}/custom/themes"
omz_plugin_dir: "{{ omz_install_dir }}/custom/plugins"

peco_version: "v0.5.11"

requirement_packages:
  - "acl"
  - "bzip2"
  - "software-properties-common"
  - "sshpass"
  - "tree"
  - "unzip"
  - "zip"

aliases: []
# aliases:
#   - command: "g"
#     target: "git"
#   - command: "gs"
#     target: "git status"
