---
- name: "Install mise plugin for java latest versions"
  ansible.builtin.include_tasks: "mise_versions.yaml"
  vars:
    plugin_name: "java"
    plugin_lib_version: "openjdk-25"
    current_version: true

- name: "Install mise plugin for java legacy versions"
  ansible.builtin.include_tasks: "mise_versions.yaml"
  vars:
    plugin_name: "java"
    plugin_lib_version: "{{ item }}"
    current_version: false
  loop:
    - "openjdk-21"
    - "openjdk-17"
    - "openjdk-11"
    - "corretto-8"

- name: "Install mise plugin for JVM build-tools"
  ansible.builtin.include_tasks: "mise_versions.yaml"
  vars:
    plugin_name: "{{ item }}"
    plugin_lib_version: "latest"
    current_version: true
  loop:
    - "gradle"
    - "maven"

- name: "Install mise plugin for kotlin"
  ansible.builtin.include_tasks: "mise_versions.yaml"
  vars:
    plugin_name: "kotlin"
    plugin_lib_version: "latest"
    current_version: true
