---
- name: "Configure git"
  community.general.git_config:
    scope: "global"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ git_configs }}"

- name: "Install mise plugin for VCS utils"
  ansible.builtin.include_tasks: "mise_versions.yaml"
  vars:
    plugin_name: "{{ item }}"
    plugin_lib_version: "latest"
    current_version: true
  loop:
    - "github-cli"
    - "act"
    - "action-validator"
    - "actionlint"
