---
##################################################################
# homebrew
##################################################################
brew_install_script_path: "{{ tmp_dir }}/brew_install.sh"
homebrew_bin: "/home/linuxbrew/.linuxbrew/bin/brew"
brew_package_dir: "/home/linuxbrew/.linuxbrew/bin"

##################################################################
# mise
##################################################################
mise_bin: "{{ brew_package_dir }}/mise"
mise_shims: "/home/{{ ansible_user }}/.local/share/mise/shims"

##################################################################
# go
##################################################################
go_bin: "{{ brew_package_dir }}/go"

##################################################################
# vcs
##################################################################
git_configs: []
# git_configs:
#   - name: "user.name"
#     value: "<git user>"
#   - name: "user.email"
#     value: "<git email>"
#   - name: "color.ui"
#     value: "auto"

##################################################################
# ssh
##################################################################
ssh_configs:
  - alias: ""
    host_name: ""
    remote_user: ""
    compression: false
    key_file: ""
    private_key: ""
#   proxy_jump: ""
